name: Build Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-windows-msvc:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure CMake (MSVC 32bit)
        run: cmake -S . -B build-32bit -A Win32 -DCP_STATIC=ON -DCMAKE_CONFIGURATION_TYPES="Release"
      - name: Build (MSVC 32bit)
        run: cmake --build build-32bit --config Release
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ConsolePauser-windows-msvc-x86-static
          path: build-32bit/Release/ConsolePauser.exe
          
      - name: Configure CMake (MSVC 64bit)
        run: cmake -S . -B build-64bit -A x64 -DCP_STATIC=ON -DCMAKE_CONFIGURATION_TYPES="Release"
      - name: Build (MSVC 64bit)
        run: cmake --build build-64bit --config Release
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: ConsolePauser-windows-msvc-x64-static
          path: build-64bit/Release/ConsolePauser.exe

  build-windows-msys2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: |
            mingw-w64-i686-gcc
            mingw-w64-i686-cmake
            mingw-w64-i686-ninja
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
          
      - name: Configure CMake (MSYS2 MINGW32)
        run: |
          set MSYSTEM=MINGW32
          msys2 -c 'cmake -B build-mingw32 -G "Ninja" -DCP_STATIC=ON -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release'
      - name: Build (MSYS2 MINGW32)
        run: msys2 -c 'cmake --build build-mingw32'
      - name: Archive results (MSYS2 MINGW32)
        uses: actions/upload-artifact@v4
        with:
          name: ConsolePauser-windows-mingw-x86-static
          path: build-mingw32/ConsolePauser.exe
        
      - name: Configure CMake (MSYS2 MINGW64)
        run: |
          set MSYSTEM=MINGW64
          msys2 -c 'cmake -B build-mingw64 -G "Ninja" -DCP_STATIC=ON -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release'
      - name: Build (MSYS2 MINGW64)
        run: msys2 -c 'cmake --build build-mingw64'
      - name: Archive results (MSYS2 MINGW64)
        uses: actions/upload-artifact@v4
        with:
          name: ConsolePauser-windows-mingw-x64-static
          path: build-mingw64/ConsolePauser.exe
  
  build-linux-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: sudo apt-get install -y gcc gcc-multilib cmake ninja-build
        
      - name: Configure CMake (Linux i386)
        run: cmake -S . -B build-i386 -G Ninja -DCP_STATIC=ON -DCMAKE_C_COMPILER=gcc -DCMAKE_C_FLAGS=-m32 -DCMAKE_BUILD_TYPE=Release
      - name: Build (Linux i386)
        run: cmake --build build-i386 --config Release
      - name: Archive results (i386)
        uses: actions/upload-artifact@v4
        with:
          name: ConsolePauser-linux-i386-static
          path: |
            build-i386/consolepauser
        
      - name: Configure CMake (Linux x86_64)
        run: cmake -S . -B build-x86_64 -G Ninja -DCP_STATIC=ON -DCMAKE_C_COMPILER=gcc -DCMAKE_C_FLAGS=-m64 -DCMAKE_BUILD_TYPE=Release
      - name: Build (Linux x86_64)
        run: cmake --build build-x86_64 --config Release
      - name: Archive results (x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: ConsolePauser-linux-x86_64-static
          path: |
            build-x86_64/consolepauser
